"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.9.

Environment Variables:
  DEBUG          - "True" for development (default: "False")
  SECRET_KEY     - Required in production, auto-generated in dev
  ALLOWED_HOSTS  - Comma-separated hosts (default: "localhost,127.0.0.1")
  CORS_ORIGINS   - Comma-separated CORS origins (default: dev localhost)
"""

import os
from pathlib import Path
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load .env file
load_dotenv(BASE_DIR / ".env")


# =============================================================================
# SECURITY SETTINGS (Environment-driven)
# =============================================================================

# DEBUG: Default to False (safe for production)
DEBUG = os.getenv("DEBUG", "False").lower() in ("true", "1", "yes")

# SECRET_KEY: Must be set in production
_secret_key_env = os.environ.get("SECRET_KEY")
if _secret_key_env:
    SECRET_KEY = _secret_key_env
elif DEBUG:
    # Development fallback - NEVER use in production
    SECRET_KEY = "django-insecure-dev-only-key-do-not-use-in-production"
else:
    raise ValueError(
        "SECRET_KEY environment variable is required in production mode. "
        "Generate one with: python -c \"from django.core.management.utils import get_random_secret_key; print(get_random_secret_key())\""
    )

# ALLOWED_HOSTS: From environment or safe defaults
_allowed_hosts_env = os.getenv("ALLOWED_HOSTS", "")
if _allowed_hosts_env:
    ALLOWED_HOSTS = [h.strip() for h in _allowed_hosts_env.split(",") if h.strip()]
else:
    # Development defaults
    ALLOWED_HOSTS = ["127.0.0.1", "localhost"]
    if DEBUG:
        # Add local network IPs for mobile app testing in dev
        ALLOWED_HOSTS += ["192.168.0.162", "192.168.31.78"]


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    # сторонние библиотеки
    "corsheaders",
    "rest_framework",
    "rest_framework.authtoken",

    # наши приложения
    "apps.accounts",
    "apps.locations",
    "apps.jobs",
    "apps.maintenance",
    "apps.api",
    "apps.marketing",
]


AUTH_USER_MODEL = "apps_accounts.User"


MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]


ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# =============================================================================
# Database (Environment-driven)
# =============================================================================

# Support DATABASE_URL for production (postgres://user:pass@host:port/db)
_database_url = os.environ.get("DATABASE_URL")
if _database_url:
    import urllib.parse
    url = urllib.parse.urlparse(_database_url)
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': url.path[1:],  # Remove leading slash
            'USER': url.username,
            'PASSWORD': url.password,
            'HOST': url.hostname,
            'PORT': url.port or '5432',
            'CONN_MAX_AGE': 600,  # Connection pooling
            'OPTIONS': {
                'connect_timeout': 10,
            },
        }
    }
else:
    # Development: SQLite
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization

LANGUAGE_CODE = 'en-us'

TIME_ZONE = "Asia/Dubai"

USE_I18N = True
USE_TZ = True


# Static files

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"


# Media (uploads)
# ВАЖНО: media лежит в backend/media, без вложенных директорий по умолчанию

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"


# Default primary key field type

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# DRF

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.TokenAuthentication",
        "rest_framework.authentication.SessionAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
}


# =============================================================================
# CORS Settings (Environment-driven)
# =============================================================================
#
# PRODUCTION: Set CORS_ORIGINS env var to your frontend domain(s)
#   Example: CORS_ORIGINS=https://app.cleanproof.com
#
# SECURITY: Wildcards (*) are NEVER allowed. Each origin must be explicit.
# =============================================================================

_cors_origins_env = os.getenv("CORS_ORIGINS", "")
if _cors_origins_env:
    # Production: explicit origins from environment
    CORS_ALLOWED_ORIGINS = [o.strip() for o in _cors_origins_env.split(",") if o.strip()]
else:
    # Development defaults (Vite default + legacy ports)
    CORS_ALLOWED_ORIGINS = [
        "http://localhost:5173",   # Vite default
        "http://127.0.0.1:5173",
        "http://localhost:8080",   # Legacy/alternative
        "http://127.0.0.1:8080",
        "http://localhost:8081",
        "http://127.0.0.1:8081",
    ]

# SECURITY: Never allow all origins — explicitly disabled
CORS_ALLOW_ALL_ORIGINS = False
# =============================================================================
# Email (SMTP via Gmail)
# =============================================================================

# Recipient for system emails (demo requests, contact messages, job reports)
FOUNDER_DEMO_EMAIL = os.getenv("FOUNDER_DEMO_EMAIL", "photobp2019@gmail.com")

# Email backend: SMTP in production, console in dev if not configured
_email_password = os.environ.get("EMAIL_HOST_PASSWORD")
if _email_password or not DEBUG:
    EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
else:
    # Development: print emails to console if no password configured
    EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"

EMAIL_HOST = os.getenv("EMAIL_HOST", "smtp.gmail.com")
EMAIL_PORT = int(os.getenv("EMAIL_PORT", "587"))
EMAIL_USE_TLS = os.getenv("EMAIL_USE_TLS", "True").lower() in ("true", "1", "yes")

# Sender email
EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER", "reports.cleanproof@gmail.com")

# App Password from environment (NEVER hardcode in production)
EMAIL_HOST_PASSWORD = _email_password or ""

# Default sender
DEFAULT_FROM_EMAIL = os.getenv(
    "DEFAULT_FROM_EMAIL",
    "CleanProof Reports <reports.cleanproof@gmail.com>"
)


# =============================================================================
# Logging Configuration
# =============================================================================

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "{levelname} {asctime} {module} {message}",
            "style": "{",
        },
        "simple": {
            "format": "{levelname} {message}",
            "style": "{",
        },
    },
    "filters": {
        "require_debug_true": {
            "()": "django.utils.log.RequireDebugTrue",
        },
        "require_debug_false": {
            "()": "django.utils.log.RequireDebugFalse",
        },
    },
    "handlers": {
        "console": {
            "level": "DEBUG" if DEBUG else "INFO",
            "class": "logging.StreamHandler",
            "formatter": "simple",
        },
        "console_production": {
            "level": "WARNING",
            "filters": ["require_debug_false"],
            "class": "logging.StreamHandler",
            "formatter": "verbose",
        },
    },
    "root": {
        "handlers": ["console"],
        "level": "DEBUG" if DEBUG else "INFO",
    },
    "loggers": {
        "django": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
        "django.request": {
            "handlers": ["console"],
            "level": "WARNING" if not DEBUG else "DEBUG",
            "propagate": False,
        },
        # Suppress noisy loggers in production
        "django.security.DisallowedHost": {
            "handlers": ["console"],
            "level": "CRITICAL",  # Don't log disallowed host attacks
            "propagate": False,
        },
    },
}


# =============================================================================
# Security Headers (Production)
# =============================================================================

if not DEBUG:
    # HTTPS settings
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
    SECURE_SSL_REDIRECT = os.getenv("SECURE_SSL_REDIRECT", "True").lower() in ("true", "1", "yes")
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True

    # HSTS
    SECURE_HSTS_SECONDS = 31536000  # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True

    # Other security headers
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = "DENY"

    # CSRF trusted origins (required for Django 4.0+)
    _csrf_trusted = os.getenv("CSRF_TRUSTED_ORIGINS", "")
    if _csrf_trusted:
        CSRF_TRUSTED_ORIGINS = [o.strip() for o in _csrf_trusted.split(",") if o.strip()]
    else:
        # Default to CORS origins if not explicitly set
        CSRF_TRUSTED_ORIGINS = CORS_ALLOWED_ORIGINS.copy()
