# Generated by Django 5.2.9 on 2026-02-14 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_accounts', '0007_add_plan_tier'),
        ('apps_maintenance', '0001_initial_asset_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_categories', to='apps_accounts.company')),
            ],
            options={
                'verbose_name_plural': 'Maintenance categories',
                'ordering': ['name'],
                'unique_together': {('company', 'name')},
            },
        ),
    ]
