# Generated by Django 5.2.9 on 2026-02-15 19:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_accounts', '0007_add_plan_tier'),
        ('apps_jobs', '0009_add_job_context'),
        ('apps_locations', '0003_add_context_to_checklisttemplate'),
        ('apps_maintenance', '0002_add_maintenance_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecurringVisitTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('frequency', models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly'), ('custom', 'Custom Interval')], default='monthly', max_length=20)),
                ('interval_days', models.PositiveIntegerField(default=30, help_text="Used when frequency='custom'. Interval in days between visits.")),
                ('start_date', models.DateField(help_text='First possible visit date')),
                ('end_date', models.DateField(blank=True, help_text='Optional: Stop generating visits after this date', null=True)),
                ('scheduled_start_time', models.TimeField(blank=True, null=True)),
                ('scheduled_end_time', models.TimeField(blank=True, null=True)),
                ('manager_notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(blank=True, help_text='Optional: Link recurring visits to specific asset', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recurring_templates', to='apps_maintenance.asset')),
                ('assigned_technician', models.ForeignKey(blank=True, help_text='Default technician for generated visits', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recurring_template_assignments', to=settings.AUTH_USER_MODEL)),
                ('checklist_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recurring_maintenance_templates', to='apps_locations.checklisttemplate')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_visit_templates', to='apps_accounts.company')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_recurring_templates', to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(help_text='Required: Location for all generated visits', on_delete=django.db.models.deletion.CASCADE, related_name='recurring_maintenance_templates', to='apps_locations.location')),
                ('maintenance_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recurring_templates', to='apps_maintenance.maintenancecategory')),
            ],
            options={
                'verbose_name': 'Recurring Visit Template',
                'verbose_name_plural': 'Recurring Visit Templates',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='GeneratedVisitLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_date', models.DateField()),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_visits', to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_source', to='apps_jobs.job')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_visits', to='apps_maintenance.recurringvisittemplate')),
            ],
            options={
                'verbose_name': 'Generated Visit Log',
                'verbose_name_plural': 'Generated Visit Logs',
                'ordering': ['-scheduled_date'],
                'unique_together': {('template', 'scheduled_date')},
            },
        ),
    ]
