# Generated by Django 5.2.9 on 2026-02-15 21:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_accounts', '0007_add_plan_tier'),
        ('apps_locations', '0003_add_context_to_checklisttemplate'),
        ('apps_maintenance', '0003_recurringvisittemplate_generatedvisitlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='warranty_end_date',
            field=models.DateField(blank=True, help_text='End date of manufacturer warranty', null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='warranty_notes',
            field=models.TextField(blank=True, help_text='Additional warranty terms or notes'),
        ),
        migrations.AddField(
            model_name='asset',
            name='warranty_provider',
            field=models.CharField(blank=True, help_text='Warranty provider or manufacturer name', max_length=200),
        ),
        migrations.AddField(
            model_name='asset',
            name='warranty_start_date',
            field=models.DateField(blank=True, help_text='Start date of manufacturer warranty', null=True),
        ),
        migrations.CreateModel(
            name='ServiceContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Contract name or title', max_length=200)),
                ('contract_number', models.CharField(blank=True, help_text='External contract reference number', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('customer_name', models.CharField(blank=True, help_text='Customer or client name', max_length=200)),
                ('customer_contact', models.CharField(blank=True, help_text='Customer contact (phone/email)', max_length=200)),
                ('contract_type', models.CharField(choices=[('service', 'Service Agreement'), ('warranty', 'Warranty Service'), ('preventive', 'Preventive Maintenance')], default='service', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('start_date', models.DateField(help_text='Contract start date')),
                ('end_date', models.DateField(blank=True, help_text='Contract end date (null = open-ended)', null=True)),
                ('service_terms', models.TextField(blank=True, help_text='Service terms, SLA commitments, scope of work')),
                ('visits_included', models.PositiveIntegerField(blank=True, help_text='Number of visits included in contract (informational)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_contracts', to='apps_accounts.company')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_contracts', to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(blank=True, help_text='Specific location covered by this contract (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_contracts', to='apps_locations.location')),
            ],
            options={
                'verbose_name': 'Service Contract',
                'verbose_name_plural': 'Service Contracts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='recurringvisittemplate',
            name='service_contract',
            field=models.ForeignKey(blank=True, help_text='Optional: Link recurring visits to a service contract', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recurring_templates', to='apps_maintenance.servicecontract'),
        ),
    ]
