# Generated by Django 5.2.9 on 2026-01-29 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_accounts', '0003_company_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Если False — компания в read-only режиме (нет новых действий).'),
        ),
        migrations.AddField(
            model_name='company',
            name='suspended_at',
            field=models.DateTimeField(blank=True, help_text='Когда компанию перевели в suspended (для ручного контроля).', null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='suspended_reason',
            field=models.CharField(blank=True, help_text='Короткая причина блокировки (видна только в админке).', max_length=255),
        ),
    ]
