# Generated by Django 5.2.9 on 2026-02-12 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_accounts', '0004_company_is_active_company_suspended_at_and_more'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='user',
            name='users_role_valid',
        ),
        migrations.AddField(
            model_name='user',
            name='auth_type',
            field=models.CharField(choices=[('password', 'Password'), ('sso', 'SSO')], default='password', help_text='Authentication method: password or SSO', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='notification_preferences',
            field=models.JSONField(blank=True, default=dict, help_text='User notification settings: email_notifications, job_assignment_alerts, weekly_summary'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner'), ('manager', 'Manager'), ('staff', 'Staff'), ('cleaner', 'Cleaner')], max_length=20),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(('role__in', ['owner', 'manager', 'staff', 'cleaner'])), name='users_role_valid'),
        ),
    ]
