# Generated by Django 5.2.9 on 2026-02-12 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_accounts', '0005_remove_user_users_role_valid_user_auth_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='must_change_password',
            field=models.BooleanField(default=False, help_text='User must change password on next login (set after reset-access)'),
        ),
    ]
