# Generated by Django 5.2.9 on 2026-02-13 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_accounts', '0006_add_must_change_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='plan_tier',
            field=models.CharField(choices=[('standard', 'Standard'), ('pro', 'Pro'), ('enterprise', 'Enterprise')], default='standard', help_text='Pricing tier: standard ($29), pro ($79), enterprise ($199)', max_length=20),
        ),
    ]
