# Generated by Django 5.2.9 on 2026-01-15 12:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_jobs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobcheckevent',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='jobcheckevent',
            name='event_time',
        ),
        migrations.RemoveField(
            model_name='jobchecklistitem',
            name='completed_at',
        ),
        migrations.RemoveField(
            model_name='jobchecklistitem',
            name='job',
        ),
        migrations.RemoveField(
            model_name='jobchecklistitem',
            name='notes',
        ),
        migrations.AddField(
            model_name='jobcheckevent',
            name='distance_m',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobcheckevent',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_check_events_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jobchecklistitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='jobchecklistitem',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_checklist_item_actions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='job',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='jobcheckevent',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='jobcheckevent',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobcheckevent',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
