# Generated by Django 5.2.9 on 2026-01-15 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_jobs', '0002_alter_jobcheckevent_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobchecklistitem',
            name='user',
        ),
        migrations.AddField(
            model_name='jobchecklistitem',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='checklist_items', to='apps_jobs.job'),
        ),
    ]
