# Generated by Django 5.2.9 on 2026-02-04 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_jobs', '0004_file_jobphoto'),
        ('apps_locations', '0002_location_latitude_location_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jobs', to='apps_locations.location'),
        ),
    ]
