# Generated by Django 5.2.9 on 2026-02-11 20:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_jobs', '0005_alter_job_location'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='force_complete_reason',
            field=models.TextField(blank=True, help_text='Reason provided by manager for force-completing this job'),
        ),
        migrations.AddField(
            model_name='job',
            name='force_completed_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when manager force-completed this job', null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='force_completed_by',
            field=models.ForeignKey(blank=True, help_text='Manager who force-completed this job', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='force_completed_jobs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='job',
            name='verification_override',
            field=models.BooleanField(default=False, help_text='True if job was force-completed without full proof verification'),
        ),
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In progress'), ('completed', 'Completed'), ('completed_unverified', 'Completed (Unverified)'), ('cancelled', 'Cancelled')], default='scheduled', max_length=30),
        ),
        migrations.AlterField(
            model_name='jobcheckevent',
            name='event_type',
            field=models.CharField(choices=[('check_in', 'Check-in'), ('check_out', 'Check-out'), ('force_complete', 'Force Complete')], max_length=20),
        ),
    ]
