# Generated by Django 5.2.9 on 2026-02-14 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_jobs', '0006_job_force_complete_reason_job_force_completed_at_and_more'),
        ('apps_maintenance', '0001_initial_asset_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='asset',
            field=models.ForeignKey(blank=True, help_text='Optional link to asset for maintenance service visits', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='apps_maintenance.asset'),
        ),
    ]
