# Generated by Django 5.2.9 on 2026-02-14 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_jobs', '0007_add_asset_fk'),
        ('apps_maintenance', '0002_add_maintenance_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='maintenance_category',
            field=models.ForeignKey(blank=True, help_text='Optional category for maintenance service visits (e.g., Preventive, Corrective)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='apps_maintenance.maintenancecategory'),
        ),
    ]
