# Generated by Django 5.2.9 on 2026-02-15 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_jobs', '0009_add_job_context'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], db_index=True, default='low', help_text='Priority level: low, medium, high', max_length=10),
        ),
        migrations.AddField(
            model_name='job',
            name='sla_deadline',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Deadline for SLA compliance. Visual timer shows time remaining.', null=True),
        ),
    ]
