# Generated by Django 5.2.9 on 2025-12-24 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_locations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
