# Generated by Django 5.2.9 on 2026-02-15 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_locations', '0002_location_latitude_location_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklisttemplate',
            name='context',
            field=models.CharField(choices=[('cleaning', 'Cleaning'), ('maintenance', 'Maintenance')], db_index=True, default='cleaning', max_length=20),
        ),
    ]
