# Generated by Django 5.2.9 on 2026-01-28 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DemoRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('role', models.CharField(blank=True, max_length=64)),
                ('cleaner_count', models.CharField(blank=True, max_length=32)),
                ('contact', models.CharField(max_length=255)),
                ('country', models.CharField(blank=True, max_length=128)),
                ('primary_pain', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
