# Generated by Django 5.2.9 on 2026-01-28 19:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0002_contactmessage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportEmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_id', models.BigIntegerField()),
                ('kind', models.CharField(choices=[('job_report', 'Job report'), ('weekly_report', 'Weekly report'), ('monthly_report', 'Monthly report')], max_length=20)),
                ('job_id', models.BigIntegerField(blank=True, null=True)),
                ('period_from', models.DateField(blank=True, null=True)),
                ('period_to', models.DateField(blank=True, null=True)),
                ('to_email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('failed', 'Failed')], default='sent', max_length=10)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_email_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Report email log',
                'verbose_name_plural': 'Report email logs',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['company_id', 'kind', 'status', 'created_at'], name='marketing_r_company_8df9d3_idx'), models.Index(fields=['company_id', 'created_at'], name='marketing_r_company_3092f9_idx')],
            },
        ),
    ]
