# Generated by Django 5.2.9 on 2026-02-12 19:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('apps_accounts', '0006_add_must_change_password'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('cleaner_created', 'Cleaner created'), ('password_reset', 'Password reset'), ('status_changed', 'Cleaner status changed')], help_text='Type of access action', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(blank=True, help_text='Additional context (e.g., new_status for status changes)', null=True)),
                ('cleaner', models.ForeignKey(help_text='Cleaner whose access was modified', on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(help_text='Company where the action occurred', on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='apps_accounts.company')),
                ('performed_by', models.ForeignKey(help_text='Manager/Owner who performed the action', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performed_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'access_audit_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['company', '-created_at'], name='access_audi_company_430c6c_idx'), models.Index(fields=['cleaner', '-created_at'], name='access_audi_cleaner_33ade4_idx')],
            },
        ),
    ]
