# Generated by Django 5.2.9 on 2026-02-13 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessauditlog',
            name='action',
            field=models.CharField(choices=[('cleaner_created', 'Cleaner created'), ('password_reset', 'Password reset'), ('status_changed', 'Cleaner status changed'), ('login_success', 'Login success'), ('deactivated', 'Deactivated'), ('reactivated', 'Reactivated')], help_text='Type of access action', max_length=50),
        ),
    ]
